version: "3.8"

services:
  ollama:
    image: ollama/ollama
    container_name: mistral
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    entrypoint: >
      sh -c "
      ollama serve &
      sleep 2 &&
      ollama pull mistral &&
      tail -f /dev/null
      "

volumes:
  ollama:
